apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../gateway/app-httproute.yaml
  - ../../gateway/api-httproute.yaml
  - ../../gateway/auth-httproute.yaml
  - ../../monitoring/grafana-httproute.yaml

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: app-route
      namespace: default
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: demo.budgetanalyzer.org
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: api-route
      namespace: default
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: demo.budgetanalyzer.org
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: auth-route
      namespace: default
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: demo.budgetanalyzer.org
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: grafana-route
      namespace: monitoring
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: grafana.budgetanalyzer.org
