apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    app.kubernetes.io/component: infrastructure
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
