#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=deploy/scripts/lib/common.sh
# shellcheck disable=SC1091 # Resolved through SCRIPT_DIR at runtime; run shellcheck -x when following sources.
source "${SCRIPT_DIR}/lib/common.sh"

DEFAULT_OUTPUT_DIR="${HOME}/.local/share/budget-analyzer/vault-secrets"
DEFAULT_GENERATED_ENV_FILE="${DEFAULT_OUTPUT_DIR}/phase-5-generated-secrets.env"
readonly DEFAULT_OUTPUT_DIR
readonly DEFAULT_GENERATED_ENV_FILE

GENERATED_ENV_FILE="${DEFAULT_GENERATED_ENV_FILE}"
OUTPUT_DIR="$(dirname "${GENERATED_ENV_FILE}")"

GENERATED_SECRET_SPECS=(
    "POSTGRES_ADMIN_PASSWORD|budget-analyzer-postgres-admin-password"
    "POSTGRES_TRANSACTION_SERVICE_PASSWORD|budget-analyzer-postgres-transaction-svc"
    "POSTGRES_CURRENCY_SERVICE_PASSWORD|budget-analyzer-postgres-currency-svc"
    "POSTGRES_PERMISSION_SERVICE_PASSWORD|budget-analyzer-postgres-permission-svc"
    "TRANSACTION_PREVIEW_IMPORT_TOKEN_ENCRYPTION_SECRET|budget-analyzer-transaction-preview-import-token-encryption-secret"
    "RABBITMQ_ADMIN_PASSWORD|budget-analyzer-rabbitmq-admin-password"
    "RABBITMQ_CURRENCY_SERVICE_PASSWORD|budget-analyzer-rabbitmq-currency-svc"
    "REDIS_DEFAULT_PASSWORD|budget-analyzer-redis-default-password"
    "REDIS_OPS_PASSWORD|budget-analyzer-redis-ops-password"
    "REDIS_SESSION_GATEWAY_PASSWORD|budget-analyzer-redis-session-gateway"
    "REDIS_EXT_AUTHZ_PASSWORD|budget-analyzer-redis-ext-authz"
    "REDIS_CURRENCY_SERVICE_PASSWORD|budget-analyzer-redis-currency-svc"
)
readonly GENERATED_SECRET_SPECS

usage() {
    cat <<'EOF'
Usage: ./deploy/scripts/12-bootstrap-phase-5-vault-secrets.sh [options]

Creates the OCI Vault secret inventory for all plain-text secrets:
  - prompts for AUTH0 client secret and FRED API key only if those OCI secrets
    do not already exist
  - generates strong random values for PostgreSQL, RabbitMQ, Redis, and
    transaction preview import token encryption
  - stores the generated values in an operator-only file outside the repo so
    the RabbitMQ definitions JSON can be assembled manually afterward
  - creates any missing OCI Vault secrets, while leaving existing secrets
    unchanged

This script intentionally does NOT create:
  - budget-analyzer-rabbitmq-definitions

Options:
  --generated-env-file FILE  Operator-only file for the generated secrets.
                             Default: ~/.local/share/budget-analyzer/vault-secrets/phase-5-generated-secrets.env
  -h, --help                 Show this help text.
EOF
}

ensure_not_container_execution() {
    if [[ -f "/.dockerenv" || -f "/run/.containerenv" ]]; then
        phase4_die "run this script from the OCI host, Cloud Shell, or another trusted machine outside the AI/container workspace"
    fi
}

prepare_output_path() {
    mkdir -p "${OUTPUT_DIR}"
    OUTPUT_DIR="$(cd "${OUTPUT_DIR}" && pwd)"
    GENERATED_ENV_FILE="${OUTPUT_DIR}/$(basename "${GENERATED_ENV_FILE}")"

    case "${GENERATED_ENV_FILE}" in
        "${PHASE4_REPO_ROOT}"|"${PHASE4_REPO_ROOT}/"*)
            phase4_die "refusing to store generated secret material under ${PHASE4_REPO_ROOT}; use a path outside the repo"
            ;;
    esac
}

prompt_for_secret() {
    local prompt="$1"
    local value

    while true; do
        read -r -s -p "${prompt}: " value
        printf '\n'

        if [[ -n "${value}" ]]; then
            printf '%s\n' "${value}"
            return 0
        fi

        phase4_warn "value cannot be empty"
    done
}

vault_secret_exists() {
    local secret_name="$1"

    oci secrets secret-bundle get-secret-bundle-by-name \
        --secret-name "${secret_name}" \
        --vault-id "${OCI_VAULT_OCID}" >/dev/null 2>&1
}

base64_encode_secret() {
    printf '%s' "$1" | base64 | tr -d '\n'
}

generate_secret_value() {
    openssl rand -hex 32
}

write_generated_env_file() {
    umask 077

    cat <<EOF > "${GENERATED_ENV_FILE}"
# Generated by deploy/scripts/12-bootstrap-phase-5-vault-secrets.sh
# Keep this file outside the repo and delete it after budget-analyzer-rabbitmq-definitions
# has been created and the values are safely recorded in OCI Vault.

POSTGRES_ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
POSTGRES_TRANSACTION_SERVICE_PASSWORD=${POSTGRES_TRANSACTION_SERVICE_PASSWORD}
POSTGRES_CURRENCY_SERVICE_PASSWORD=${POSTGRES_CURRENCY_SERVICE_PASSWORD}
POSTGRES_PERMISSION_SERVICE_PASSWORD=${POSTGRES_PERMISSION_SERVICE_PASSWORD}
TRANSACTION_PREVIEW_IMPORT_TOKEN_ENCRYPTION_SECRET=${TRANSACTION_PREVIEW_IMPORT_TOKEN_ENCRYPTION_SECRET}
RABBITMQ_ADMIN_PASSWORD=${RABBITMQ_ADMIN_PASSWORD}
RABBITMQ_CURRENCY_SERVICE_PASSWORD=${RABBITMQ_CURRENCY_SERVICE_PASSWORD}
REDIS_DEFAULT_PASSWORD=${REDIS_DEFAULT_PASSWORD}
REDIS_OPS_PASSWORD=${REDIS_OPS_PASSWORD}
REDIS_SESSION_GATEWAY_PASSWORD=${REDIS_SESSION_GATEWAY_PASSWORD}
REDIS_EXT_AUTHZ_PASSWORD=${REDIS_EXT_AUTHZ_PASSWORD}
REDIS_CURRENCY_SERVICE_PASSWORD=${REDIS_CURRENCY_SERVICE_PASSWORD}
EOF

    chmod 600 "${GENERATED_ENV_FILE}"
}

load_or_generate_secret_material() {
    local generated_values=()
    local spec
    local variable_name

    if [[ -f "${GENERATED_ENV_FILE}" ]]; then
        phase4_info "reusing generated secret material from ${GENERATED_ENV_FILE}"
        set -a
        # shellcheck disable=SC1090
        source "${GENERATED_ENV_FILE}"
        set +a
    else
        phase4_info "generating fresh PostgreSQL, RabbitMQ, Redis, and transaction preview import token secrets"
    fi

    for spec in "${GENERATED_SECRET_SPECS[@]}"; do
        variable_name="${spec%%|*}"
        if [[ -z "${!variable_name:-}" ]]; then
            printf -v "${variable_name}" '%s' "$(generate_secret_value)"
            generated_values+=("${variable_name}")
        fi
    done

    if (( ${#generated_values[@]} > 0 )); then
        write_generated_env_file
        phase4_info "stored generated secret material in ${GENERATED_ENV_FILE}"
        phase4_info "generated values: ${generated_values[*]}"
    fi
}

require_generated_values() {
    local missing=()
    local spec
    local variable_name

    for spec in "${GENERATED_SECRET_SPECS[@]}"; do
        variable_name="${spec%%|*}"
        if [[ -z "${!variable_name:-}" ]]; then
            missing+=("${variable_name}")
        fi
    done

    if (( ${#missing[@]} > 0 )); then
        phase4_die "generated password file is missing required values: ${missing[*]}"
    fi
}

create_secret_if_missing() {
    local secret_name="$1"
    local secret_value="$2"

    if vault_secret_exists "${secret_name}"; then
        phase4_info "vault secret already exists, leaving unchanged: ${secret_name}"
        return 0
    fi

    phase4_info "creating vault secret: ${secret_name}"
    oci vault secret create-base64 \
        --compartment-id "${OCI_COMPARTMENT_OCID}" \
        --vault-id "${OCI_VAULT_OCID}" \
        --key-id "${OCI_VAULT_KEY_OCID}" \
        --secret-name "${secret_name}" \
        --secret-content-content "$(base64_encode_secret "${secret_value}")" \
        --wait-for-state ACTIVE \
        --max-wait-seconds 1200 >/dev/null
}

create_generated_secrets() {
    local spec
    local variable_name
    local secret_name

    for spec in "${GENERATED_SECRET_SPECS[@]}"; do
        variable_name="${spec%%|*}"
        secret_name="${spec#*|}"
        create_secret_if_missing "${secret_name}" "${!variable_name}"
    done
}

create_prompted_secret_if_missing() {
    local secret_name="$1"
    local prompt="$2"
    local secret_value

    if vault_secret_exists "${secret_name}"; then
        phase4_info "vault secret already exists, leaving unchanged: ${secret_name}"
        return 0
    fi

    secret_value="$(prompt_for_secret "${prompt}")"
    create_secret_if_missing "${secret_name}" "${secret_value}"
}

main() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --generated-env-file)
                GENERATED_ENV_FILE="${2:-}"
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                phase4_die "unknown option: $1"
                ;;
        esac
        shift
    done

    OUTPUT_DIR="$(dirname "${GENERATED_ENV_FILE}")"

    ensure_not_container_execution
    prepare_output_path

    phase4_require_commands oci openssl
    phase4_load_instance_env
    phase4_require_env_vars OCI_COMPARTMENT_OCID OCI_VAULT_OCID OCI_VAULT_KEY_OCID

    load_or_generate_secret_material
    require_generated_values

    create_prompted_secret_if_missing \
        "budget-analyzer-auth0-client-secret" \
        "Enter AUTH0_CLIENT_SECRET"
    create_prompted_secret_if_missing \
        "budget-analyzer-fred-api-key" \
        "Enter FRED API key"

    create_generated_secrets

    phase4_info "created or confirmed every plain-text vault secret except budget-analyzer-rabbitmq-definitions"
    phase4_warn "next step: build budget-analyzer-rabbitmq-definitions using the RabbitMQ passwords in ${GENERATED_ENV_FILE}, then create that final OCI secret manually"
}

main "$@"
