apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: infrastructure
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqps
      port: 5671
      targetPort: 5671
    - name: management
      port: 15672
      targetPort: 15672
