apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-ingress-gateway-config
  namespace: istio-ingress
data:
  deployment: |
    spec:
      template:
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  service: |
    spec:
      type: NodePort
      ports:
        - port: 443
          nodePort: 30443
  serviceAccount: |
    automountServiceAccountToken: true
