pilot:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
meshConfig:
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  extensionProviders:
    - name: ext-authz-http
      envoyExtAuthzHttp:
        service: ext-authz.default.svc.cluster.local
        port: 9002
        headersToUpstreamOnAllow:
          - x-user-id
          - x-roles
          - x-permissions
        includeRequestHeadersInCheck:
          - cookie
        failOpen: false
