apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastructure

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: redis-acl-bootstrap
    namespace: infrastructure
    files:
      - start-redis.sh=start-redis.sh

generatorOptions:
  disableNameSuffixHash: true
