apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: tracing
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: tracing
  ports:
    - name: grpc-otlp
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      appProtocol: grpc
    - name: http-otlp
      port: 4318
      targetPort: otlp-http
      protocol: TCP
      appProtocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: monitoring
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: tracing
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: tracing
  ports:
    - name: query-http
      port: 16686
      targetPort: query-http
      protocol: TCP
    - name: query-grpc
      port: 16685
      targetPort: query-grpc
      protocol: TCP
